# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @tokyo-night-tmux_theme storm  
set -g @tokyo-night-tmux_transparent 1
set -g @tokyo-night-tmux_show_music 1
set -g @tokyo-night-tmux_show_netspeed 1
set -g @tokyo-night-tmux_netspeed_iface "wlan0" 
set -g @tokyo-night-tmux_netspeed_showip 1      
set -g @tokyo-night-tmux_netspeed_refresh 1     
set -g @tokyo-night-tmux_window_tidy_icons 0

bind -n M-H resize-pane -L 5
bind -n M-J resize-pane -D 5
bind -n M-K resize-pane -U 5
bind -n M-L resize-pane -R 5

setw -g mode-keys vi
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"

# Start window numbering from 1 and auto renumber windows
set -g base-index 1
set -g renumber-windows on

bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"

# Copy mode (vi)
setw -g copy-mode-match-style "bg=#bcb5b5,fg=#010101"
setw -g copy-mode-current-match-style "bg=#ffffff,fg=#010101"

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
