backend = "glx";
vsync = false;

blur-background = true;
blur-background-frame = true;
blur-background-fixed = true;

corner-radius = 0;
shadow = false;
transparent-clipping = false;

blur: {
    method = "dual_kawase";
    strength = 5;
};

blur-background-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'"
];

opacity-rule = [
  "80:class_g = 'org.gnome.Nautilus'"
];
