backend = "glx";
vsync = true;

blur-background = true;
blur-background-frame = false;
blur-background-fixed = true;

blur: {
	method = "dual_kawase";
	strength = 5;
};

blur-background-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'"
];

opacity-rule = [
    "80:class_g = 'org.gnome.Nautilus'"
];
