backend = "glx";
vsync = false;

blur-background = true;
blur-background-frame = true;
blur-background-fixed = true;

blur: {
    method = "dual_kawase";
    strength = 5;
};

blur-background-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'"
];
